### ISSUE TITLE
Unreadable text on selection

### ISSUE THREAD

**Issue by mukeshgurpude** [adambard/learnxinyminutes-site#93]
<img width="275" alt="image" src="https://user-images.githubusercontent.com/55982424/149462678-8029ff61-bdae-42b7-a8d8-c562f705f4d7.png">

https://github.com/adambard/learnxinyminutes-site/blob/15d8e77e806513bff680f16749d0d7b02dace359/source/css/dark.css.scss#L1

Solution will be just to add one more rule to change color on selection
```scss
html.dark {
    ::selection {
        color: #000;
    }
}
```
